### ISSUE TITLE
Remove grunt

### ISSUE THREAD

**Issue by sveisvei** [gardr/sample-project#18]
"Grunt does not work well when used in dependencies." - conclusion.

Either make a ./scripts/ or ./tasks/with buildsteps, more granulated.

Current gruntfile does: 
# pre
- Installing bower dependencies
- jshint
# tasks
- run tests / karma
- generate html
- maven release
- js
  - browserify
  - minify
- watch

Maven install should of course stay where it is, but generating resources should be standalone scripts or examples, and less dependencies.

**Comment by gregersrygg** [comment]
The only tasks we should have is for jshint and running tests. The rest doesn't belong in the core.
- Bower is only used for a cookie library. Many sites have one already, so it's better that they just pass a function that can get a cookie. But the functionality that is using the cookies should be a plugin, and not part of the core.
- Maven releases should be part of our FINN-internal gardr wrapper project.
- The html template is so plain and simple that I think it's best we just show an example in the readme that can be copy-pasted
- Browserify and minify should be done by those using Gar∂r, so they get a bundle with only what they need.

**Comment by gregersrygg** [comment]
Grunt is gone now :)
